language: python

python:
  - 2.7.1

cache: pip

install:
  - pip install coveralls
  - pip install coverage
  - pip install flask
env:
  repo_token: Buoj6FpNTHFOjix4MjVDjXYL5oSP95TZ0

script:
  - nosetests --with-coverage --cover-package=app

after_success: coveralls

